""" .vimrc

"""
""" Peter Tersløv Forsberg <ptrf@pronoia.dk>
""" 2009-2014 - Feel free to copy as much as you want

""" Remap of mapleader - <leader>
let mapleader = ","

""" Setup variable g:my_vim_dir for VIMDIR s
let g:my_vim_dir=expand("$HOME/.vim")


""" Behavioral
set nocompatible
set noinsertmode
set bs=2
set incsearch
set hlsearch
set showmatch
set path=.,~/
set updatecount=50
set ttyfast
set report=0
set nomodeline
set visualbell
set shortmess=atI
" Start scrolling three lines before the horizontal window border
set scrolloff=3
" Show the current mode
set showmode
set noerrorbells
" Don’t reset cursor to start of line when moving around.
set nostartofline
set autoread
set autowrite
" Enhance command-line completion
set wildmenu
" Don’t add empty newlines at the end of files
set binary
set noeol
" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed
" Ignore case of searches
set ignorecase

""" Input
set backspace=indent,eol,start
set expandtab
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set pastetoggle=<Leader>p
" Use UTF-8 without BOM
set encoding=utf-8 nobomb

""" Terminal variables.
set t_Co=256
set t_ti=
set t_te=

""" Mmm, inkpot. Plus, we like syntax hilighting!
colorscheme inkpot
syntax on

""" Remove no from nocursorcolumn to get fancy crosshair
set nocursorcolumn
set cursorline

""" Backup, swaps, undos, etc.
set backup
set backupdir=~/.vim/backups/
set swapfile
set directory=~/.vim/swaps/
set undolevels=1000
set undodir=~/.vim/undofiles

""" Encoding, file formats
set enc=utf-8
set tenc=utf-8
set fileformat=unix

""" Visual appearance
" Keep at least 3 lines above and below cursor
set so=3
set nonumber
set ruler
set laststatus=2

""" GUI options
" Font face and no toolbar
set gfn=Inconsolata
set go=acgi


""""
"""" REMAPS
""""

"""" MOVEMENT
" Make tab jump to next bracket
nnoremap <tab> %
vnoremap <tab> %

" Make arrow keys useless
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Easy move between splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Make j and k move up and down, regardless of line wraps etc.
nnoremap j gj
nnoremap k gk

map <C-S-k> <C-]>
map <C-S-j> <C-t>

" Sudo to write
if has("unix")
    cmap w!! w !sudo tee % >/dev/null
end

"""
""" LEADERS
"""

" :nohlsearch
nnoremap <leader><space> :noh<cr>

" :vsplit, move focus to new window
nnoremap <leader>w <C-w>v<C-w>l

" reformat paragraph
nnoremap <leader>q gqip

" put a line of ='s below the current line w/ same width
nnoremap <leader>1 yypVr=
nnoremap <leader>2 yypVr-

" Save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>

"""
""" FUNCTIONS
"""

""" If we have a nice font, we want tabs and trails to show visually.
if (&termencoding == "utf-8") || has("gui_running")
    if v:version >= 700
        set list listchars=tab:▸\ ,trail:·,extends:…,nbsp:‗,eol:¬
    else
        set list listchars=tab:»·,trail:·,extends:…
    endif
else
    if v:version >= 700
        set list listchars=tab:>-,trail:.,extends:>,nbsp:_
    else
        set list listchars=tab:>-,trail:.,extends:>
    endif
endif

""" Make sure we have needed directories in place
if has("unix") || has("win32") || has("win64")
    if !isdirectory(expand("~/.vim/"))
        !mkdir -p ~/.vim/backups/
        !mkdir -p ~/.vim/swaps/
        !mkdir -p ~/.vim/undofiles/
    endif
endif

if has("folding")
    set foldenable
    set foldmethod=indent
    set foldlevelstart=99
endif

if has("title")
    set title
endif

if has("eval")
    filetype on
    filetype indent on
    filetype plugin on
endif

if has("autocmd")
    autocmd BufNewFile,BufRead *.txt                     setf txt
    autocmd FileType mail,txt set nohlsearch formatoptions+=t textwidth=72 nonu
    autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
    autocmd BufNewFile,BufRead *.md setfiletype markdown syntax=markdown
endif

"""
""" OS SPECIFICS
"""

""" Windows
" Copied from
" http://stackoverflow.com/questions/10612362/setting-up-gvim-on-windows
" $HOME/.vim and $HOME/.vim/after are in the &rtp on unix But on windows, they
" need to be added.
if has("win32") || has("win64")
  "add g:my_vim_dir to the front of the runtimepath
  execute "set rtp^=".g:my_vim_dir
  "add g:my_vim_dir\after to the end of the runtimepath
  execute "set rtp+=".g:my_vim_dir."\\after"
  "Note, pathogen#infect() looks for the 'bundle' folder in each path
  "of the &rtp, where the last dir in the '&rtp path' is not 'after'. The
  "<path>\bundle\*\after folders will be added if and only if
  "the corresponding <path>\after folder is in the &rtp before
  "pathogen#infect() is called.  So it is very important to add the above
  "'after' folder.
  "(This applies to vim plugins such as snipmate, tabularize, etc.. that
  " are loaded by pathogen (and perhaps vundle too.))

  " Not necessary, but I like to cleanup &rtp to use \ instead of /
  " when on windows machines
  let &rtp=substitute(&rtp,"[/]","\\","g")

  "On windows, if called from cygwin or msys, the shell needs to be changed 
  "to cmd.exe to work with certain plugins that expect cmd.exe on windows versions   
  "of vim.
  if &shell=~#'bash$'
    set shell=$COMSPEC " sets shell to correct path for cmd.exe
  endif
endif

"""
""" PLUGINS
"""

""" Pathogen infect
execute pathogen#infect()

""" markdown mode
let g:vim_markdown_initial_foldlevel=1

""" Secure modelines
let g:secure_modelines_verbose = 1
let g:secure_modelines_modelines = 15

""" Github comment
let g:github_user = 'ptrf'
let g:github_comment_open_browser = 1

""" Git gutter
let g:gitgutter_eager = 1
